#! /bin/bash

fav_nums=(3.14 2.123. 4.32 5.434)

echo "Pi is ${fav_nums[0]}"

fav_nums[4]=1.414

echo "GR : ${fav_nums[4]}"

for i in ${fav_nums[*]}; do
	echo $i
done


for i in ${fav_nums[@]}; do
	echo $i
done

echo "Array length is : ${#fav_nums[@]}"

sorted_nums=($(for i in "${fav_nums[@]}"; do
	echo $i
done | sort))

for i in ${sorted_nums[*]}; do
	echo $i
done

unset 'sorted_nums[1]'
unset sorted_nums


